# Default SOPS config that specify what to use for encryption, and where to be encrypted.
creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    azure_keyvault: # Azure KeyVault URL  https://demo123.vault.azure.net/keys/demo-secret-key/c12231211
