apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: bluesky-secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
  interval: 20s
  path: ./clusters/play/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
