apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sops
  namespace: flux-system
spec:
  interval: 20s
  dependsOn:
  - name: flux-system
  path: ./clusters/play/sops
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
